
extend type Query {
	security: SecurityDemo
}

type SecurityDemo {
	public: String
	protected: String
	roleFoo: String
	roleBarBaz: String
	protected2: String @authenticated
}

directive @authenticated on FIELD_DEFINITION
