type Article {
    id: ID!
    title: String!
    content: String!
    category: Category!
}

type Category {
    id: ID!
    name: String!
}


type Todo {
    id: ID!
    title: String!
    todoStatus: TodoStatus!
}

scalar TodoTitle

enum TodoStatus {
    TODO
    DOING
    DONE
}

input CreateTodo {
    title: TodoTitle!
}

input UpdateTodo {
    id: ID!
    title: TodoTitle
    todoStatus: TodoStatus
}

type Query {
    article(id: ID!): Article
    articles: [Article!]!
    categories: [Category!]!
    allTodo: [Todo!]!
    findTodo(id: ID!): Todo
}

type Mutation {
    createCategory(name: String!): Category!
    createArticle(title: String!, content: String!, categoryId: ID!): Article!
    createTodo(input: CreateTodo!): Todo!
    updateTodo(input: UpdateTodo!): Todo!
    deleteTodo(id: ID!): ID!
}
